language: node_js

sudo: required

node_js:
- 14
  
before_install:
- npm i -g npm@latest
- sudo apt-get install npm
- sudo npm i -g npx

before_script:
- sudo npx playwright install --with-deps

script:
- npm run build
- npm test

